services:
  nginx:
    image: 'nginx:1.21.3'
    container_name: nginx
    depends_on:
      - phpfpm
    ports:
      - '80:80'
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./www:/var/www/html:cached
  phpfpm:
    build: './dockerfile/phpfpm'
    container_name: php72
    volumes:
      - ./www:/var/www/html:cached
      - ./config/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:cached
# Network
networks:
    default:
      name: magento 

